### PR TITLE
Update OpenShift registry to use www-auth header

### PR DESCRIPTION
**Pull request by dymurray**
* hit `<registry_route>/v2/` and check the returned `www-authenticate` header to get bearer token URL
* Contact URL from step one with basic auth to retrieve bearer token
* Use in requests to get manifests

### CODE REVIEW

**Review by shawn-hurley — APPROVED** [review]
LGTM w/ the adding the test case

**Review by djzager — CHANGES_REQUESTED** [review]
I'm with @shawn-hurley I think a unit test for this would be great. I think the `rhcc` adapter has a good unit test, if you need another example, there is one in [my pr](https://github.com/automationbroker/bundle-lib/pull/40/files#diff-dcc0d02d4bf32f405d79f21da9da733c).

**Review by eriknelson — CHANGES_REQUESTED** [review]
Waiting on test case.

**Comment by dymurray** [comment]
@eriknelson @djzager working on test cases.

**Review by djzager — APPROVED** [review]
Thanks for going through that pain. LGTM

**Comment by shawn-hurley** [comment]
Merging because we were waiting on the test case.

**Pull request merged**
