### PR TITLE
Don't error out if we have images in config for apiv2 adapter

### PR DESCRIPTION
**Pull request by dymurray**

### CODE REVIEW

**Review by shawn-hurley — APPROVED** [review]

**Review by shawn-hurley — DISMISSED** [review]
Sorry, we should add a test case for this I think

**Comment by eriknelson** [comment]
+1 for a test.

**Comment by johnkim76** [comment]
LGTM

**Review by shawn-hurley — APPROVED** [review]

**Review by jmrodri — APPROVED** [review]
ACK

**Pull request merged**
