### PR TITLE
fix race condition, stack the defers instead.

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by jmrodri** [comment]
### Race Condition detected

`go test -race -run TestDeprovision`

```
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
==================
WARNING: DATA RACE
Write at 0x00000259eee0 by goroutine 16:
  github.com/automationbroker/bundle-lib/bundle.TestDeprovision.func20()
      /home/jesusr/dev/src/github.com/automationbroker/bundle-lib/bundle/deprovision_test.go:482 +0x8c
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:777 +0x16d

Previous read at 0x00000259eee0 by goroutine 15:
  github.com/automationbroker/bundle-lib/bundle.(*executor).Deprovision.func1.1()
      /home/jesusr/dev/src/github.com/automationbroker/bundle-lib/bundle/deprovision.go:86 +0x157
  github.com/automationbroker/bundle-lib/bundle.(*executor).Deprovision.func1()
      /home/jesusr/dev/src/github.com/automationbroker/bundle-lib/bundle/deprovision.go:115 +0xc17

Goroutine 16 (running) created at:
  testing.(*T).Run()
      /usr/lib/golang/src/testing/testing.go:824 +0x564
  github.com/automationbroker/bundle-lib/bundle.TestDeprovision()
      /home/jesusr/dev/src/github.com/automationbroker/bundle-lib/bundle/deprovision_test.go:481 +0x3c51
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:777 +0x16d

Goroutine 15 (finished) created at:
  github.com/automationbroker/bundle-lib/bundle.(*executor).Deprovision()
      /home/jesusr/dev/src/github.com/automationbroker/bundle-lib/bundle/deprovision.go:43 +0x3c4
  github.com/automationbroker/bundle-lib/bundle.TestDeprovision.func20()
      /home/jesusr/dev/src/github.com/automationbroker/bundle-lib/bundle/deprovision_test.go:487 +0x300
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:777 +0x16d
==================
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="state: present for service instance copying to bundle namespace"
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: "
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=error msg="No image field found on the apb instance.Spec (apb.yaml)"
time="2018-07-10T00:43:43-04:00" level=error msg="apb instance.Spec requires [name] and [image] fields to be separate"
time="2018-07-10T00:43:43-04:00" level=error msg="Are you trying to run a legacy ansibleapp without an image field?"
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=error msg="Problem executing bundle create sandbox [bundle-486704f6-b178-4f0e-8330-8583be073efe] deprovision"
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=error msg="unable to copy secrets: [] to  new namespace"
time="2018-07-10T00:43:43-04:00" level=error msg="Problem executing bundle [bundle-37189d74-585d-432b-8b32-9adb54ab963f] deprovision"
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=error msg="Deprovision action failed - unable to watch runnign bundle"
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:43:43-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:43:43-04:00" level=info msg="============================================================"
time="2018-07-10T00:43:43-04:00" level=error msg="unable to delete the extracted credentials - unable to delete extracted cred"
--- FAIL: TestDeprovision (0.02s)
    --- FAIL: TestDeprovision/deprovison_successfully_stae_is_presetn (0.00s)
    	testing.go:730: race detected during execution of test
	testing.go:730: race detected during execution of test
time="2018-07-10T00:43:43-04:00" level=error msg="failed to delete state for instance d302544e-83fb-11e8-a4e5-c85b76145add : unable to delete state "
FAIL
exit status 1
FAIL	github.com/automationbroker/bundle-lib/bundle	0.222s
```

**Comment by jmrodri** [comment]
### Condition fixed

`go test -race -run TestDeprovision`

```
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="state: present for service instance copying to bundle namespace"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: "
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=error msg="No image field found on the apb instance.Spec (apb.yaml)"
time="2018-07-10T00:44:48-04:00" level=error msg="apb instance.Spec requires [name] and [image] fields to be separate"
time="2018-07-10T00:44:48-04:00" level=error msg="Are you trying to run a legacy ansibleapp without an image field?"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=error msg="Problem executing bundle create sandbox [bundle-a3787a30-fd83-43cc-9fbf-39087c72e147] deprovision"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=error msg="unable to copy secrets: [] to  new namespace"
time="2018-07-10T00:44:48-04:00" level=error msg="Problem executing bundle [bundle-1f294644-034e-4f9f-9174-ad967e5dcf72] deprovision"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=error msg="Deprovision action failed - unable to watch runnign bundle"
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="                      DEPROVISIONING                        "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Id: new-spec-id"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Name: new-fq-name"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Image: new-image"
time="2018-07-10T00:44:48-04:00" level=info msg="ServiceInstance.Description: "
time="2018-07-10T00:44:48-04:00" level=info msg="============================================================"
time="2018-07-10T00:44:48-04:00" level=error msg="unable to delete the extracted credentials - unable to delete extracted cred"
time="2018-07-10T00:44:48-04:00" level=error msg="failed to delete state for instance f9bbd841-83fb-11e8-8489-c85b76145add : unable to delete state "
PASS
ok  	github.com/automationbroker/bundle-lib/bundle	1.217s
```

**Review by maleck13 — COMMENTED** [review]
Not sure why this solves a race condition? Perhaps I am not getting it, would like to learn though. 
Previously we had a single defer which means a single function pushed onto the stack and executed immediately after the current function exits. In that function we had two synchronous function calls. One to delete the state and the other to remove the sandbox.
Now we have two defers which call each the functions separately. If my understanding is correct this means two functions pushed onto the stack and executed in LIFO order synchronously. So as before the state gets removed and then the sandbox is destroyed.

**Comment by shawn-hurley** [comment]
@jmrodri I wonder if this solves the immediate problem but does not solve the larger issue with testing this. 

> 2. Deferred function calls are executed in Last In First Out order after the surrounding function returns. [1](https://blog.golang.org/defer-panic-and-recover)

I think this means that the go routine finishes, the test.Run starts a new test, which changes the runtime while the defer call is happening and therefore we get the race condition. Stacking these defers might cause the race condition to not show up anymore but I am sure that we can easily make a test, in provision or bind or unbind that could cause the same issue. I am wondering if this is a fundamental design flaw that I introduced.

**Review by shawn-hurley — APPROVED** [review]

**Review by dymurray — APPROVED** [review]

**Comment by jmrodri** [comment]
@maleck13 while chatting with @shawn-hurley the theory is that when you do a `defer runtime.Provider.DestroySandbox` vs `defer func()` the defer adds the actual `DestroySandbox` to the stack. If it changes it can continue moving forward. But when it's `defer func()` it has to evaluate the `DestroySandbox` thus causing the read and the race condition since it was changed underneath it.  That is our hypothesis.

Ultimately, the test case is identical to the `provision` and `update` tests. They do not exhibit the problem. The only difference was that they had a defer directly on the `DestroySandbox` while `deprovision` was on a `func()`. After trying a variety of things, this was the one that worked.

**Pull request merged**
